## The two functions makeCacheMatrix and cacheSolve work together to set the inverse of 
## a given matrix in the cache and retrieve it, if the inverse of the same matrix is
## to be calculated again. 

## The makeCacheMatrix function takes a matrix as input and returns a list of
## four functions: 1) set the value of the matrix 2) get the value of the matrix
## 3) set the inverse of the matrix 4) get the inverse of the matrix

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y) {
                x <<- y
                inv <<- NULL
        }
        get <- function() x 
        setinverse <- function(inverse) inv <<- inverse
        getinverse <- function() inv
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## The cacheSolve function takes the list generated by the makeCacheMatrix function
## as input and checks if the inverse of the matrix has already been calculated.
## If the inverse of the matrix has already been calculated, the solution is retrieved 
## from the cache, instead of calculating it again, 
## and a short message is displayed. 
## Otherwise the inverse of the matrix is calculated and the value of the matrix is set
## in the cache via the setinverse function
## The set() function isn't used in this example, but could be used to set the 
## input-matrix in the parent environment to a different value, changing the output of
## the other three functions. 


cacheSolve <- function(x, ...) {
      inv <- x$getinverse()
      if(!is.null(inv)) {
              message("getting cached data")
              return(inv)
      }
      data <- x$get()
      inv <- solve(data)
      x$setinverse(inv)
      inv
}
